// Type Imports
import type { PropertyListType } from '@/types/apps/propertyTypes'

export const db: PropertyListType = {
  content: [
    {
      id: 1,
      code: 'yuck',
      name: 'while',
      description: 'since fluff weary',
      type: 'CASA',
      price: 15208.73,
      curCode: 'CLP',
      shared: false,
      numberOfBedrooms: 13915,
      numberOfBathrooms: 16206,
      yearBuilt: 10860,
      m2Built: 1359.78,
      m2SemiCovered: 13936.6,
      area: 2304.9,
      address: 'since',
      zip: 'confound guest',
      city: 'Bilbao',
      x: 9052.51,
      y: 8964.56,
      state: 'DISPONIBLE',
      organization: null,
      owner: null
    },
    {
      id: 5,
      code: 'when curse blah',
      name: 'yahoo',
      description: 'fooey finally',
      type: 'DEPARTAMENTO',
      price: 32275.82,
      curCode: 'USD',
      shared: true,
      numberOfBedrooms: 930,
      numberOfBathrooms: 5454,
      yearBuilt: 14967,
      m2Built: 26500.27,
      m2SemiCovered: 878.51,
      area: 3696.5,
      address: 'who pigpen',
      zip: 'whoa politely mealy',
      city: 'Zamora',
      x: 28519.32,
      y: 23416.37,
      state: 'NODISPONIBLE',
      organization: null,
      owner: null
    },
    {
      id: 1505,
      code: 'test4',
      name: 'test4',
      description: 'test4',
      type: 'DEPARTAMENTO',
      price: 1000,
      curCode: 'USD',
      shared: false,
      numberOfBedrooms: 1,
      numberOfBathrooms: 1,
      yearBuilt: 2000,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'DISPONIBLE',
      organization: null,
      owner: null
    },
    {
      id: 1514,
      code: 'test12',
      name: 'test12',
      description: 'test12',
      type: 'TERRENO',
      price: 3000,
      curCode: 'UF',
      shared: true,
      numberOfBedrooms: 0,
      numberOfBathrooms: 0,
      yearBuilt: 0,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 100000,
      y: 200000,
      state: 'BORRADOR',
      organization: null,
      owner: null
    },
    {
      id: 1516,
      code: 'test14',
      name: 'test14',
      description: 'test14',
      type: 'DEPARTAMENTO',
      price: 25000,
      curCode: 'UF',
      shared: true,
      numberOfBedrooms: 0,
      numberOfBathrooms: 0,
      yearBuilt: 0,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'RESERVADA',
      organization: [Object],
      owner: [Object]
    },
    {
      id: 1517,
      code: 'test15',
      name: 'test15',
      description: 'test15',
      type: 'TERRENO',
      price: 1000,
      curCode: 'UF',
      shared: false,
      numberOfBedrooms: 1,
      numberOfBathrooms: 2,
      yearBuilt: 0,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'RESERVADA',
      organization: [Object],
      owner: [Object]
    },
    {
      id: 1518,
      code: 'test16',
      name: 'test16',
      description: 'test16',
      type: 'TERRENO',
      price: 150000,
      curCode: 'CLP',
      shared: true,
      numberOfBedrooms: 4,
      numberOfBathrooms: 2,
      yearBuilt: 0,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'BORRADOR',
      organization: null,
      owner: null
    },
    {
      id: 1519,
      code: 'test17',
      name: 'test17',
      description: 'test17',
      type: 'PARCELA',
      price: 15000000,
      curCode: 'CLP',
      shared: true,
      numberOfBedrooms: 4,
      numberOfBathrooms: 4,
      yearBuilt: 2020,
      m2Built: 150,
      m2SemiCovered: 200,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'RESERVADA',
      organization: [Object],
      owner: [Object]
    },
    {
      id: 1520,
      code: 'test18',
      name: 'test18',
      description: 'test18',
      type: 'DEPARTAMENTO',
      price: 15000,
      curCode: 'UF',
      shared: false,
      numberOfBedrooms: 3,
      numberOfBathrooms: 3,
      yearBuilt: 2025,
      m2Built: 150,
      m2SemiCovered: 100,
      area: 1500,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'BORRADOR',
      organization: null,
      owner: null
    },
    {
      id: 1521,
      code: 'test19',
      name: 'test19',
      description: 'test19',
      type: 'CASA',
      price: 2600,
      curCode: 'UF',
      shared: false,
      numberOfBedrooms: 0,
      numberOfBathrooms: 0,
      yearBuilt: 0,
      m2Built: 0,
      m2SemiCovered: 0,
      area: 0,
      address: '',
      zip: '',
      city: '',
      x: 0,
      y: 0,
      state: 'BORRADOR',
      organization: null,
      owner: null
    }
  ],
  totalElements: 11
}