import type { Offer, AuditLog } from "@/types/types"

// Datos de ejemplo para propiedades, agentes y contactos
export const mockProperties = {
  1: { name: "Apartamento Centro", address: "Calle Mayor 10" },
  2: { name: "Villa Playa", address: "Paseo Marítimo 25" },
  3: { name: "Local Centro", address: "Gran Vía 45" },
  4: { name: "Piso Universidad", address: "Calle Universidad 8" },
  5: { name: "Chalet Sierra", address: "Camino Montaña 12" },
}

export const mockAgents = {
  1: { name: "Ana García", avatar: "AG", id: 1 },
  2: { name: "Pedro Martínez", avatar: "PM", id: 2 },
  3: { name: "Laura Fernández", avatar: "LF", id: 3 },
  4: { name: "Carlos López", avatar: "CL", id: 4 },
  5: { name: "María Rodríguez", avatar: "MR", id: 5 },
}

export const mockLeads = {
  1: { name: "Carlos Rodríguez", email: "carlos@example.com" },
  2: { name: "Laura Sánchez", email: "laura@example.com" },
  3: { name: "Miguel Torres", email: "miguel@example.com" },
  4: { name: "Isabel Díaz", email: "isabel@example.com" },
  5: { name: "Roberto Fernández", email: "roberto@example.com" },
}

export const mockOpportunities = {
  1: { name: "Apartamento Centro" },
  2: { name: "Casa Playa" },
  3: { name: "Local Comercial" },
  4: { name: "Piso Estudiantes" },
  5: { name: "Chalet Montaña" },
}

// Colores para las etapas de oferta
export const offerStageColors = {
  DRAFT: { bg: "#e3f2fd", color: "#1565c0", label: "Borrador" },
  SUBMITTED: { bg: "#f3e5f5", color: "#7b1fa2", label: "Enviada" },
  COUNTER_OFFER: { bg: "#e0f7fa", color: "#0097a7", label: "Contraoferta" },
  CONFIRM_FOR_EXCHANGE: { bg: "#fff3e0", color: "#e65100", label: "Confirmar Por Canje" },
  PENDING_CLIENT_APPROVAL: { bg: "#e8f5e9", color: "#2e7d32", label: "Pendiente Visar Cliente" },
  PENDING_CAPTURER_APPROVAL: { bg: "#f1f8e9", color: "#558b2f", label: "Pendiente Visar Captador" },
  PENDING_PLACER_APPROVAL: { bg: "#f9fbe7", color: "#827717", label: "Pendiente Visar Colocador" },
  PENDING_OWNER_APPROVAL: { bg: "#fffde7", color: "#f57f17", label: "Pendiente Visar Propietario" },
  ACCEPTED: { bg: "#e8f5e9", color: "#2e7d32", label: "Aceptada" },
  REJECTED: { bg: "#ffebee", color: "#c62828", label: "Rechazada" },
  EXPIRED: { bg: "#f5f5f5", color: "#757575", label: "Expirada" },
  FINALIZED: { bg: "#e0f2f1", color: "#00796b", label: "Finalizada" },
  CANCELLED: { bg: "#fafafa", color: "#424242", label: "Cancelada" },
}

// Datos de ejemplo para ofertas
export const mockOffers: Offer[] = [
  {
    id: 1,
    amount: 150000000,
    currency: "CLP",
    commission: 2,
    amountCommission: 3000000,
    currencyCommission: "CLP",
    expirationDate: "2023-12-31",
    observation: "Oferta inicial para el apartamento",
    stage: "SUBMITTED",
    swap: false,
    active: true,
    organizationId: 1,
    opportunityId: 1,
    propertyId: 1,
    prospectId: 1,
    assignAgentId: 1,
    createdAt: "2023-10-15T10:30:00",
    updatedAt: "2023-10-15T10:30:00",
  },
  {
    id: 2,
    amount: 5000,
    currency: "UF",
    commission: 1.5,
    amountCommission: 75,
    currencyCommission: "UF",
    expirationDate: "2023-11-30",
    observation: "Oferta con posibilidad de canje por propiedad más pequeña",
    stage: "COUNTER_OFFER",
    swap: true,
    active: true,
    organizationId: 1,
    opportunityId: 2,
    propertyId: 2,
    prospectId: 2,
    assignAgentId: 2,
    createdAt: "2023-10-10T14:20:00",
    updatedAt: "2023-10-12T09:15:00",
  },
  {
    id: 3,
    amount: 120000,
    currency: "USD",
    commission: 3,
    amountCommission: 3600,
    currencyCommission: "USD",
    expirationDate: "2023-12-15",
    stage: "ACCEPTED",
    swap: false,
    active: true,
    organizationId: 1,
    opportunityId: 3,
    propertyId: 3,
    prospectId: 3,
    assignAgentId: 3,
    createdAt: "2023-10-05T11:45:00",
    updatedAt: "2023-10-08T16:30:00",
  },
  {
    id: 4,
    amount: 85000000,
    currency: "CLP",
    commission: 2.5,
    amountCommission: 2125000,
    currencyCommission: "CLP",
    expirationDate: "2023-11-20",
    observation: "Oferta para estudiantes, incluye algunos muebles",
    stage: "REJECTED",
    swap: false,
    active: false,
    organizationId: 1,
    opportunityId: 4,
    propertyId: 4,
    prospectId: 4,
    assignAgentId: 4,
    createdAt: "2023-09-28T09:00:00",
    updatedAt: "2023-10-02T13:20:00",
  },
  {
    id: 5,
    amount: 8500,
    currency: "UF",
    commission: 2,
    amountCommission: 170,
    currencyCommission: "UF",
    expirationDate: "2023-12-10",
    stage: "DRAFT",
    swap: false,
    active: true,
    organizationId: 1,
    opportunityId: 5,
    propertyId: 5,
    prospectId: 5,
    assignAgentId: 5,
    createdAt: "2023-10-18T15:10:00",
    updatedAt: "2023-10-18T15:10:00",
  },
]

// Datos de ejemplo para los logs de auditoría
export const mockAuditLogs: AuditLog[] = [
  {
    id: 1,
    offerId: 1,
    timestamp: "2023-10-15T10:30:00",
    actionType: "CREATED",
    description: "Oferta creada",
    userId: 1,
    userName: "Ana García",
  },
  {
    id: 2,
    offerId: 1,
    timestamp: "2023-10-16T11:45:00",
    actionType: "STATE_CHANGE",
    description: "Cambio de estado",
    previousValue: "DRAFT",
    newValue: "SUBMITTED",
    userId: 1,
    userName: "Ana García",
  },
  {
    id: 3,
    offerId: 2,
    timestamp: "2023-10-10T14:20:00",
    actionType: "CREATED",
    description: "Oferta creada",
    userId: 2,
    userName: "Pedro Martínez",
  },
  {
    id: 4,
    offerId: 2,
    timestamp: "2023-10-12T09:15:00",
    actionType: "STATE_CHANGE",
    description: "Cambio de estado",
    previousValue: "SUBMITTED",
    newValue: "COUNTER_OFFER",
    userId: 2,
    userName: "Pedro Martínez",
  },
  {
    id: 5,
    offerId: 3,
    timestamp: "2023-10-05T11:45:00",
    actionType: "CREATED",
    description: "Oferta creada",
    userId: 3,
    userName: "Laura Fernández",
  },
  {
    id: 6,
    offerId: 3,
    timestamp: "2023-10-06T16:30:00",
    actionType: "STATE_CHANGE",
    description: "Cambio de estado",
    previousValue: "DRAFT",
    newValue: "SUBMITTED",
    userId: 3,
    userName: "Laura Fernández",
  },
  {
    id: 7,
    offerId: 3,
    timestamp: "2023-10-08T16:30:00",
    actionType: "STATE_CHANGE",
    description: "Cambio de estado",
    previousValue: "SUBMITTED",
    newValue: "ACCEPTED",
    userId: 3,
    userName: "Laura Fernández",
  },
]
