import type { KanbanType } from '@/types/apps/kanbanTypes'

export const db: KanbanType = {
  columns: [
    {
      id: 1,
      title: 'Contacto Inicial',
      taskIds: [1, 2]
    },
    {
      id: 2,
      title: 'Calificado',
      taskIds: [3]
    },
    {
      id: 3,
      title: 'Visita Programada',
      taskIds: [5, 6]
    },
    {
      id: 4,
      title: 'Propuesta',
      taskIds: [7]
    },
    {
      id: 5,
      title: 'Negociación',
      taskIds: [8,4]
    },
    {
      id: 6,
      title: 'Cerrado Ganado',
      taskIds: [9]
    },
    {
      id: 7,
      title: 'Cerrado Perdido',
      taskIds: [10]
    }
  ],
  tasks: [
    {
      id: 1,
      title: 'Compra Apartamento Las Condes',
      badgeText: ['Departamento'],
      attachments: 4,
      comments: 12,
      stage: 'Contacto Inicial',
      opportunity: {
        id: 1,
        name: "Compra Apartamento Las Condes",
        prospect: "Juan Pérez",
        amount: 250000000,
        curCode: "CLP",
        probability: 80,
        stage: "INITIAL_CONTACT",
        source: "TocToc",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Cliente interesado en apartamento de 3 dormitorios en Las Condes",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Apartamento Las Condes"],
      },
      assigned: [
        { src: '/images/avatars/1.png', name: 'Ana Silva' },
        { src: '/images/avatars/5.png', name: 'Juan Pérez' },
        { src: '/images/avatars/4.png', name: 'Sebastian' }
      ],
      dueDate: new Date(new Date().getFullYear(), 11, 30)
    },
    {
      id: 2,
      title: 'Local Comercial en Providencia',
      opportunity: {
        id: 2,
        name: "Local Comercial en Providencia",
        prospect: "María González",
        amount: 250000000,
        curCode: "CLP",
        probability: 80,
        stage: "INITIAL_CONTACT",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Inversionista interesado en local comercial de 120m2 en Providencia",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Local Comercial Providencia"],
      },
      badgeText: ['Comercial'],
      attachments: 2,
      stage: 'Contacto Inicial',
      comments: 8,
      assigned: [
        { src: '/images/avatars/3.png', name: 'Ana Silva' },
        { src: '/images/avatars/2.png', name: 'Sebastian' }
      ],
      dueDate: new Date(new Date().getFullYear(), 5, 30)
    },
    {
      id: 3,
      title: 'Casa Familiar en La Reina',
      image: '/images/banners/properties/banner-first-step-property.png',
      badgeText: ['Casa'],
      attachments: 8,
      comments: 17,
      stage: 'Calificado',
      opportunity: {
        id: 3,
        name: "Casa Familiar en La Reina",
        prospect: "Carlos Rodríguez",
        amount: 250000000,
        curCode: "CLP",
        probability: 80,
        stage: "QUALIFICATION",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Familia buscando casa de 4 dormitorios en La Reina",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Casa La Reina"],
      },
      assigned: [
        { src: '/images/avatars/8.png', name: 'Ana Silva' },
        { src: '/images/avatars/7.png', name: 'Sebastian' }
      ],
      dueDate: new Date(new Date().getFullYear(), 8, 15)
    },
    {
      id: 4,
      title: 'Casa en Ñuñoa',
      badgeText: ['Casa'],
      attachments: 10,
      comments: 18,
      stage: 'Negociación',
      opportunity: {
        id: 4,
        name: "Casa en Ñuñoa",
        prospect: "Pedro Martínez",
        amount: 250000000,
        curCode: "CLP",
        probability: 80,
        stage: "NEGOTIATION",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Familia buscando casa de 3 dormitorios en Ñuñoa",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Casa Ñuñoa"],
      },
      assigned: [
        { src: '/images/avatars/1.png', name: 'John Doe' },
        { src: '/images/avatars/2.png', name: 'Emily Davis' },
        { src: '/images/avatars/3.png', name: 'Tom Smith' },
        { src: '/images/avatars/6.png', name: 'David Smith' }
      ],
      image: '/images/banners/properties/banner-first-step-property.png',
      dueDate: new Date(new Date().getFullYear(), 9, 20)
    },
    {
      id: 5,
      title: 'Casa en Huechuraba',
      image: '/images/banners/properties/banner-first-step-property.png',
      badgeText: ['Casa'],
      attachments: 5,
      comments: 14,
      opportunity: {
        id: 5,
        name: "Casa en Huechuraba",
        prospect: "Juan Pérez",
        amount: 200000000,
        curCode: "CLP", 
        probability: 80,  
        stage: "VISIT_SCHEDULED",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Cliente interesado en casa de 5 dormitorios en Huechuraba",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Casa Huechuraba"],
      },
      stage: 'Visita Programada',
      assigned: [
        { src: '/images/avatars/8.png', name: 'Jane Smith' },
        { src: '/images/avatars/3.png', name: 'Tom Smith' },
        { src: '/images/avatars/2.png', name: 'Emily Davis' }
      ],
      dueDate: new Date(new Date().getFullYear(), 10, 10)
    },
    {
      id: 6,
      title: 'Oficina en Las Condes',
      badgeText: ['Oficina'],
      attachments: 6,
      comments: 21,
      opportunity: {
        id: 6,
        name: "Oficina en Las Condes",
        prospect: "Roberto Sánchez",
        amount: 200000000,
        curCode: "CLP",
        probability: 80,
        stage: "VISIT_SCHEDULED",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Empresa busca oficina de 200m2 en Las Condes",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Oficina Las Condes"],
      },
      stage: 'Visita Programada',
      assigned: [{ src: '/images/avatars/4.png', name: 'Emily Davis' }],
      dueDate: new Date(new Date().getFullYear(), 11, 5)
    },
    {
      id: 7,
      title: 'Departamento en Vitacura',
      badgeText: ['Departamento'],
      attachments: 6,
      comments: 21,
      opportunity: {
        id: 7,
        name: "Departamento en Vitacura",
        prospect: "Ana López",
        amount: 200000000,
        curCode: "CLP",
        probability: 80,
        stage: "PROPOSAL",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Cliente busca departamento de 3 dormitorios en Vitacura",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Departamento Vitacura"],
      },
      stage: 'Propuesta',
      assigned: [{ src: '/images/avatars/4.png', name: 'Emily Davis' }],
      dueDate: new Date(new Date().getFullYear(), 11, 5)
    },
    {
      id: 8,
      title: 'Local Comercial en Santiago Centro',
      badgeText: ['Comercial'],
      attachments: 6,
      comments: 21,
      opportunity: {
        id: 8,
        name: "Local Comercial en Santiago Centro",
        prospect: "Luis Ramírez",
        amount: 200000000,
        curCode: "CLP",
        probability: 80,
        stage: "NEGOTIATION",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Inversionista busca local comercial de 150m2 en Santiago Centro",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
        organization: "Inmo Seba",
        assignAgent:  "Ana Silva",
        properties: ["Local Comercial Santiago Centro"],
      },
      stage: 'Negociación',
      assigned: [{ src: '/images/avatars/4.png', name: 'Emily Davis' }],
      dueDate: new Date(new Date().getFullYear(), 11, 5)
    },
    {
      id: 9,
      title: 'Departamento en Providencia',
      badgeText: ['Departamento'],
      attachments: 6,
      comments: 21,
      opportunity: {
        id: 9,
        name: "Departamento en Providencia",
        prospect: "Carmen Torres",
        amount: 200000000,
        curCode: "CLP",
        probability: 80,
        stage: "CLOSING",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Cliente busca departamento de 2 dormitorios en Providencia",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",  
        organization: "Inmo Seba",  
        assignAgent:  "Ana Silva",
        properties: ["Departamento Providencia"],
      },
      stage: 'Cerrado Ganado',
      assigned: [{ src: '/images/avatars/4.png', name: 'Emily Davis' }],
      dueDate: new Date(new Date().getFullYear(), 11, 5)
    },
    {
      id: 10,
      title: 'Oficina en El Golf',
      badgeText: ['Oficina'],
      attachments: 6,
      comments: 21,
      opportunity: {
        id: 10,
        name: "Oficina en El Golf",
        prospect: "Miguel Ángel",
        amount: 200000000,
        curCode: "CLP",
        probability: 80,
        stage: "LOST",
        source: "Portal Inmobiliario",
        expectedCloseDate: "2025-06-30T00:00:00Z",
        description: "Empresa busca oficina de 300m2 en El Golf",
        active: true,
        createdAt: "2023-03-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",  
        organization: "Inmo Seba",  
        assignAgent:  "Ana Silva",
        properties: ["Oficina El Golf"],
      },
      stage: 'Cerrado Perdido',
      assigned: [{ src: '/images/avatars/4.png', name: 'Emily Davis' }],
      dueDate: new Date(new Date().getFullYear(), 11, 5)
    }
  ]
}
